# Generated by Django 4.2 on 2024-08-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Cumbias', 'cumbias'), ('Electrónica', 'Electrónica'), ('Música Clasica', 'Música Clasica')], max_length=30),
        ),
    ]
