# Generated by Django 4.2 on 2024-08-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Música Clasica', 'Música Clasica'), ('Rock', 'Rock'), ('Electrónica', 'Electrónica'), ('Pop', 'Pop'), ('Cumbias', 'cumbias')], max_length=30),
        ),
    ]
