# Generated by Django 4.2 on 2024-08-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0003_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Electrónica', 'Electrónica'), ('Cumbias', 'cumbias'), ('Música Clasica', 'Música Clasica'), ('Pop', 'Pop')], max_length=30),
        ),
    ]
