# Generated by Django 4.2 on 2024-08-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0005_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Música Clasica', 'Música Clasica'), ('Cumbias', 'cumbias'), ('Electrónica', 'Electrónica'), ('Rock', 'Rock'), ('Pop', 'Pop')], max_length=30),
        ),
    ]
