# Generated by Django 4.2 on 2024-08-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0006_alter_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(default='artist_images/default_profile_picture.jpg', upload_to='artist_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='front_page',
            field=models.ImageField(upload_to='album_images'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Electrónica', 'Electrónica'), ('Música Clasica', 'Música Clasica'), ('Rock', 'Rock'), ('Cumbias', 'cumbias')], max_length=30),
        ),
    ]
