# Generated by Django 4.2 on 2024-08-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0007_artist_profile_picture_alter_album_front_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Música Clasica', 'Música Clasica'), ('Cumbias', 'cumbias'), ('Rock', 'Rock'), ('Electrónica', 'Electrónica'), ('Pop', 'Pop')], max_length=30),
        ),
    ]
