# Generated by Django 4.2 on 2024-08-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0008_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Electrónica', 'Electrónica'), ('Cumbias', 'cumbias'), ('Música Clasica', 'Música Clasica'), ('Rock', 'Rock')], max_length=30),
        ),
    ]
