# Generated by Django 4.2 on 2024-08-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0009_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Cumbias', 'cumbias'), ('Pop', 'Pop'), ('Electrónica', 'Electrónica'), ('Rock', 'Rock'), ('Música Clasica', 'Música Clasica')], max_length=30),
        ),
    ]
